<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="4" hostname="OPTIMUSPRIME" name="com.testNGFramework.BankingApplicationSoftDependency" tests="6" failures="1" timestamp="06 Oct 2022 10:04:50 GMT" time="0.031" errors="0">
  <testcase name="logOut" time="0.000" classname="com.testNGFramework.BankingApplicationSoftDependency">
    <skipped/>
  </testcase> <!-- logOut -->
  <testcase name="lunchApplication" time="0.023" classname="com.testNGFramework.BankingApplicationSoftDependency">
    <failure type="java.lang.AssertionError" message="expected [PageTitle] but found [noPageTitle]">
      <![CDATA[java.lang.AssertionError: expected [PageTitle] but found [noPageTitle]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testNGFramework.BankingApplicationSoftDependency.lunchApplication(BankingApplicationSoftDependency.java:11)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- lunchApplication -->
  <testcase name="closeApplication" time="0.002" classname="com.testNGFramework.BankingApplicationSoftDependency"/>
  <testcase name="checkSavingAccountBalance" time="0.000" classname="com.testNGFramework.BankingApplicationSoftDependency">
    <skipped/>
  </testcase> <!-- checkSavingAccountBalance -->
  <testcase name="loginUser" time="0.006" classname="com.testNGFramework.BankingApplicationSoftDependency">
    <skipped/>
  </testcase> <!-- loginUser -->
  <testcase name="checkCurrentAccountBalance" time="0.000" classname="com.testNGFramework.BankingApplicationSoftDependency">
    <skipped/>
  </testcase> <!-- checkCurrentAccountBalance -->
</testsuite> <!-- com.testNGFramework.BankingApplicationSoftDependency -->
